name: Metrics

on:
  schedule: [{ cron: "0 * * * *" }]  # Runs every hour
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: RockHead07
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Jakarta

          # 🎌 AniList Plugin Configuration
          plugin_anilist: yes
          plugin_anilist_user: RockHead07  # Change if your AniList username is different
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters, genres, scores
          plugin_anilist_limit: 10  # Optional: number of items shown per section
